### DISCUSSION TITLE
1.5.0-beta1

### DISCUSSION THREAD

**Discussion by ilyhalight** [ilyhalight/voice-over-translation#319] [Обновления]
# 1.5.0-beta1 (By MrSoczekXD)
⚠ Это бета версия и она может работать нестабильно. Обо всех проблемах рекомендуется сразу же сообщать в [Issues](https://github.com/ilyhalight/voice-over-translation/issues)

- Переписан UI расширения
- Переписана логика загрузки
- Добавлена возможность проигрывания нескольких переводов одновремено
- Добавлена возможность кастомизации цветов расширения через Stylish, Stulus и другие подобные расширения

  Пример изменения цветов меню на зеленый:
  ```css

  /* ==UserStyle==
  @name         VOT-GREEN
  @version      16.09.2023
  @namespace    vot-green
  @description  LLL
  @author       Toil
  @license      No License
  ==/UserStyle== */

  :root {
    --vot-primary-rgb: 201, 245, 180 ;
  }

  .vot-segmented-button[data-status="success"] .vot-translate-button {
    color: rgb(201, 245, 180);
    fill: rgb(201, 245, 180);
  }
  ```

- Добавлено версионирование переводов
- Добавлена поддержка YT Shorts
- Добавлена возможность включить кнопку PiP для браузеров в которых она поддерживается (хромиум)
- Добавлено немного информации в меню
- Добавлена возможность смены языка меню
- Кеш переводов, теперь, очищается при сбросе настроек
- Стандартный шрифт изменен на Roboto
- Возможно что-то еще, про что я забыл написать

TODO: Обновить локализацию следующих файлов:
<details>
<summary>список файлов для обновления</summary>
locales\af.json
locales\am.json
locales\az.json
locales\bg.json
locales\bs.json
locales\ca.json
locales\cy.json
locales\da.json
locales\el.json
locales\et.json
locales\eu.json
locales\fi.json
locales\gl.json
locales\hr.json
locales\hu.json
locales\hy.json
locales\km.json
locales\kn.json
locales\lo.json
locales\mk.json
locales\ml.json
locales\mn.json
locales\mt.json
locales\my.json
locales\ne.json
locales\nl.json
locales\pa.json
locales\pl.json
locales\ro.json
locales\si.json
locales\sk.json
locales\sl.json
locales\sq.json
locales\sr.json
locales\su.json
locales\sv.json
locales\sw.json
locales\uz.json
locales\zu.json
</details>

## What's Changed (autogenerated)
* VideoObserver, New UI and stuff by @MrSoczekXD in https://github.com/ilyhalight/voice-over-translation/pull/294

**Full Changelog**: https://github.com/ilyhalight/voice-over-translation/compare/1.4.1...1.5.0-beta1

<hr /><em>This discussion was created from the release <a href='https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta1'>1.5.0-beta1</a>.</em>

**Comment by FiLinX** [comment]
а можете пояснить про вот эти два пункта:
1.  "Добавлена возможность проигрывания нескольких переводов одновремено"  -  что имеется ввиду?
2.   "Кеш переводов, теперь, очищается при сбросе настроек"  - что ещё за кеш? а зачем он вообще хранился то?? и почему только по сбросу настроек этот кеш должен сбрасываться?  я не понимаю, я не хочу каких либо кешей, и не хочу настройки сбрасывать

**Reply by xirthas** [reply]
> 1. "Добавлена возможность проигрывания нескольких переводов одновремено"  -  что имеется ввиду?

Если на странице несколько видео, то ты можешь для всех включить перевод, и переключаться между ними. Например лента в тиктоке

> 2. "Кеш переводов, теперь, очищается при сбросе настроек"  - что ещё за кеш? а зачем он вообще хранился то??

Это сделано, чтобы при каждом открытии страницы, где поддерживается VOT, не запрашивать локализацию меню с сервера.

> и почему только по сбросу настроек этот кеш должен сбрасываться?

Локализацию нет нужды сбрасывать, она сломаться не может(не должна), но на всякий случай был добавлен ее сброс

> я не понимаю, я не хочу каких либо кешей, и не хочу настройки сбрасывать

10кб погоды не сделают

**Reply by ilyhalight** [reply]
Как уже сказали выше, кеш перевода нужен, чтобы постоянно не дергать файл перевода с гитхаба и соответственно загрузка меню происходила быстрее

**Comment by xirthas** [comment]
@ilyhalight 

1. Добавлена поддержка ленты tiktok
2. Опечатка Stulus -> Stylus
3. Перенеси наверное Stylus на первое место. [Stylish удаляли из магазина](https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/), что со Stylish сейчас я не знаю
4. Поменяй в [segmented-button.scss](https://github.com/ilyhalight/voice-over-translation/blob/dev/src/styles/components/segmented-button.scss) `#8ab4f8` на `rgb(var(--vot-primary-rgb, 33, 150, 243))`
5. Добавь полный пример
```css
:root {
  --vot-font-family: "Roboto", "Segoe UI", BlinkMacSystemFont, system-ui, -apple-system;

  --vot-primary-rgb: 139, 180, 245;
  --vot-onprimary-rgb: 32, 33, 36;
  --vot-surface-rgb: 32, 33, 36;
  --vot-onsurface-rgb: 227, 227, 227;

  --vot-subtitles-background: rgba(var(--vot-surface-rgb, 46, 47, 52), 0.8);
  --vot-subtitles-color: rgb(var(--vot-onsurface-rgb, 227, 227, 227));
  --vot-subtitles-passed-color: rgb(var(--vot-primary-rgb, 33, 150, 243));
}
```
